### PR TITLE
Fix capitalization of Jts directory on Linux

### PR DESCRIPTION
**Pull request by meteorpublish**

### CODE REVIEW

**Comment by rlktradewright** [comment]
Thanks for that. Every little helps!...

**Comment by meteorpublish** [comment]
Also, for the Gateway, the executable `is ~/Jts/ibgateway/NNN/ibgateway`.

**Comment by rlktradewright** [comment]
That section of the User Guide only relates to TWS, so the Gateway is irrelevant here. Or are you referring to somewhere else?

**Comment by meteorpublish** [comment]
OK, is Gateway is not affected by the auto-logoff change, feel free to close.

**Comment by meteorpublish** [comment]
OK, [if Gateway is not affected by the auto-logoff change](https://github.com/IbcAlpha/IBC/issues/49#issuecomment-484452100), feel free to close.

**Comment by rlktradewright** [comment]
Ah yes, you're right. What I wrote before was (I think) true at the time, but since then things have changed...

I'll reword the whole section  shortly.

**Comment by rlktradewright** [comment]
Oops, thanks, well spotted. Fixed.

**Pull request merged**
