### PR TITLE
Add disable localhost-only feature

### PR DESCRIPTION
**Pull request by timkpaine**
extracted from https://github.com/IbcAlpha/IBC/issues/68 by @mcbain with a bugfix for capitalization

### CODE REVIEW

**Comment by rlktradewright** [comment]
I will not accept this PR.

I've said over and over again, and will say it again, that IBC is not intended as a TWS/Gateway configuration mechanism (except in a few limited cases where there's no alternative).

So if you want to run TWS or Gateway in Docker, and you want to depend on certain configuration settings that are not 'out-of-the-box' defaults, then you need to ensure that your Docker setup includes an appropriate TWS/Gateway settings file (you can set this up on a local system and then copy it wherever you need it). Docker provides various mechanisms for storing such state data (volumes and bind mounts).

In this particular case, you don't actually need to use any of this because you can leave the default localhost-only setting in place, and use SSH tunnelling to ensure that remote connections appear to come from the localhost (this is also potentially more secure as it ensures your API connections are encrypted).

**Comment by timkpaine** [comment]
@rlktradewright No problem, I will maintain my fork

**Comment by markmark1** [comment]
Tim Where's your fork   
  
  
  
    
  

  
  
>

**Comment by timkpaine** [comment]
https://github.com/timkpaine/IBC

**Comment by mattyoungberg** [comment]
@rlktradewright, do you know the location of any documentation that shows what the `ibg.xml` file should look like? Mine is encrypted (a feature which got introduced in mid 2021, I believe) and it looks like the behavior can't be turned off. I'd love a pointer in the right direction to figure out how to do this.

However, if you're open to some pushback on your exclusion of this PR, it appears to me that the reason so many people pick IBC is to minimize, if not completely obviate in some cases, the need of a GUI. This allows automation and deployment at scale.

I figure you see the purpose of IBC is solely to manage the lifecycle of TWS/Gateway, but exceptions have been made in the past to expose configurations via the `config.ini` file for which there was "no alternative". **Except these very things could be configured by opening up a GUI and configuring them by hand.**

So it seems to me that the inferred purpose of IBC (as hinted at by you) and the community's use case for it are somewhat misaligned, and that misalignment is being invoked for the sake of not wanting scope creep to consume the time of unpaid volunteers.

This functionality of disabling that "localhost only" configuration seems to line up with this "automation" quality that people find so attractive with IBC, and you have had a PR to include it. It's also utterly common for APIs and API Gateways to sit on boxes other than their clients. I have a hard time seeing why this PR won't be allowed through for the sake of scope creep, as I imagine that its maintenance would be minimal.

Is the scope creep you're worrying about the type that assumes a GUI? Such as "put this window here, size it like this, blah blah blah"? Because this obviously isn't that. I'd totally understand NOT wanting to add features that DO assume a GUI.

Maybe your mind has changed in the past year since they've added encryption of the `ibg.xml` file? Or maybe I've misconstrued your point and you are still convinced this shouldn't be included? I think there's a strong case for including it, and the code is there to use (Thanks, @timkpaine).

**Pull request closed without merging**
