### PR TITLE
fix for #59

### PR DESCRIPTION
**Pull request by fugaz**
I think the issue is with home variable expansion.
The proposed fix works for me and should not break anything.

### CODE REVIEW

**Comment by rlktradewright** [comment]
Thanks very much. That should do the trick for this particular instance. 

But what about the other places where ~ is used, for example lines 209-210 in ibcstart.sh:

```
	if [ "$tws_path" = "" ]; then tws_path=~/Applications ;fi
	if [ "$tws_settings_path" = "" ]; then tws_settings_path=~/Jts ;fi
```

and the top-level scripts twsstartmacos.sh and gatewaystartmacos.sh? Does ~ somehow magically work in these places?

I'm really surprised that ~ doesn't seem to work in the macOS version of Bash. I tried searching in vain for some definitive information about this, so if you know of any, please let me know.

**Comment by shevkoplyas** [comment]
Richard, the ~ is only expanded by the shell if it's unquoted. When it's quoted it's a literal tilde symbol.

**Comment by rlktradewright** [comment]
Oh, thanks for that Dmitry. Obvious when you think about it!

**Comment by rlktradewright** [comment]
@fugaz 

Could you please amend this to use 

`~"/..."`

instead of 

`$HOME"/..."`

just for consistency, as I've used ~ everywhere else. (Provided it still works of course!...)

Thanks

**Comment by fugaz** [comment]
@rlktradewright - if concern is consistency, shouldn't this rather be:

	tws_vmoptions="$HOME/Jts/tws-${tws_version}.vmoptions"

or

	tws_vmoptions=~/Jts/tws-${tws_version}.vmoptions

?

**Comment by rlktradewright** [comment]
Yes. I prefer the latter since I haven't used $HOME anywhere else.

**Pull request merged**
